#!/usr/bin/env python3
"""
Generate dist/swarmnet.hpp and dist/swarmnet.cpp from the multi-file source tree.

This is intentionally deterministic:
- stable file order
- recursive inlining of local public headers
- removal of local include lines in the amalgamated .cpp
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HEADER_ORDER = [
    "core.hpp",
    "replay.hpp",
    "transport.hpp",
    "membership.hpp",
    "swarmnet.hpp",
]

SOURCE_ORDER = [
    "core.cpp",
    "membership.cpp",
    "replay.cpp",
    "transport.cpp",
    "swarmnet.cpp",
]

LOCAL_HEADER_RE = re.compile(r'^\s*#\s*include\s+"swarmnet/([^"]+)"\s*$')
PRAGMA_ONCE_RE = re.compile(r"^\s*#\s*pragma\s+once\s*$")


def _rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _flatten_header(path: Path, include_root: Path, root: Path, visited: set[Path], out: list[str]) -> None:
    real = path.resolve()
    if real in visited:
        return
    visited.add(real)

    out.append(f"// --- begin {_rel(path, root)} ---")
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        if PRAGMA_ONCE_RE.match(raw_line):
            continue

        match = LOCAL_HEADER_RE.match(raw_line)
        if match is not None:
            child = include_root / match.group(1)
            if child.exists():
                _flatten_header(child, include_root, root, visited, out)
                continue
        out.append(raw_line)
    out.append(f"// --- end {_rel(path, root)} ---")
    out.append("")


def generate(root: Path, out_dir: Path) -> tuple[Path, Path]:
    include_root = root / "include" / "swarmnet"
    src_root = root / "src"
    out_dir.mkdir(parents=True, exist_ok=True)

    header_lines: list[str] = []
    header_lines.append("// Generated by tools/amalgamate.py. Do not edit directly.")
    header_lines.append("#pragma once")
    header_lines.append("")

    visited: set[Path] = set()
    for header_name in HEADER_ORDER:
        header_path = include_root / header_name
        if not header_path.exists():
            raise FileNotFoundError(f"missing public header: {header_path}")
        _flatten_header(header_path, include_root, root, visited, header_lines)

    header_path = out_dir / "swarmnet.hpp"
    header_path.write_text("\n".join(header_lines).rstrip() + "\n", encoding="utf-8")

    cpp_lines: list[str] = []
    cpp_lines.append("// Generated by tools/amalgamate.py. Do not edit directly.")
    cpp_lines.append('#include "swarmnet.hpp"')
    cpp_lines.append("")

    for source_name in SOURCE_ORDER:
        src_path = src_root / source_name
        if not src_path.exists():
            raise FileNotFoundError(f"missing source file: {src_path}")

        cpp_lines.append(f"// --- begin {_rel(src_path, root)} ---")
        for raw_line in src_path.read_text(encoding="utf-8").splitlines():
            if LOCAL_HEADER_RE.match(raw_line):
                continue
            cpp_lines.append(raw_line)
        cpp_lines.append(f"// --- end {_rel(src_path, root)} ---")
        cpp_lines.append("")

    cpp_path = out_dir / "swarmnet.cpp"
    cpp_path.write_text("\n".join(cpp_lines).rstrip() + "\n", encoding="utf-8")
    return header_path, cpp_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SwarmNet amalgamated dist files.")
    parser.add_argument("--output", default="dist", help="Output directory for dist files.")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    out_dir = (root / args.output).resolve()
    header_path, cpp_path = generate(root, out_dir)
    print(f"generated: {header_path}")
    print(f"generated: {cpp_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
